// Generated by CoffeeScript 1.6.1
(function() {
  var BaseItem, defaults;

  defaults = {
    x: 0,
    y: 0
  };

  /*
  ## Base Item class
  
  Item classes that interact with the game logic have to extend from here
  
  E.g. Entities, Bodies, Sprites and Walls extend from BaseItem
  
  The World and Layer classes will need to always have acces to the basic
  method specified in this class
  */


  BaseItem = (function() {

    BaseItem.prototype.itemType = 'base';

    function BaseItem(options, layer) {
      this.layer = layer;
      options = $.extend(true, {}, defaults, options);
      this.x = options.x || 0;
      this.y = options.y || 0;
      this.removed = false;
    }

    BaseItem.prototype.translate = function(x, y) {
      return this.moveTo(this.x + x, this.y + y);
    };

    BaseItem.prototype.moveTo = function(x, y) {
      this.x = x;
      return this.y = y;
    };

    BaseItem.prototype.update = function() {};

    BaseItem.prototype.remove = function() {};

    return BaseItem;

  })();

  module.exports = BaseItem;

}).call(this);
