// Generated by CoffeeScript 1.6.1

/*
## Debug module

Defines debug settings - useful for debugging
*/


(function() {
  var helpers;

  helpers = require('../helpers/debug');

  module.exports = {
    skipAnimations: false,
    debugPhysics: false
  };

}).call(this);
