// Generated by CoffeeScript 1.6.1

/*
## Renderer module

Handles the storing and rendering of templates

The templates stored are Handlebars templates pre-compiled into functions
They are set in the main App file

Used to render all UI elements
*/


(function() {

  module.exports = {
    templates: {},
    compile: function(tpl) {
      if (typeof template === 'function') {
        return tpl;
      } else {
        return Handlebars.compile(tpl);
      }
    },
    set: function(id, template) {
      return this.templates[id] = typeof template === 'string' ? this.compile(template) : template;
    },
    get: function(nsString) {
      if (nsString == null) {
        nsString = null;
      }
      if (nsString != null) {
        return this.templates[nsString];
      } else {
        return this.templates;
      }
    },
    render: function(id, data) {
      if (this.get(id) != null) {
        return this.get(id)(data);
      } else if (this.get("partials/" + id) != null) {
        return this.get("partials/" + id)(data);
      } else {
        throw Error("Template '" + id + "' not found");
      }
    }
  };

}).call(this);
