// Generated by CoffeeScript 1.6.1

/*
## Base Behaviour class

This class is ment to be extended when creating a new Behaviour

Behaviours are instanciated as children of Entities and are passed their parent and their parent's
world, having so full access to manipulate the game logic

The parent Entity will call .update at every frame in the GameLoop
Read Entity for more
*/


(function() {
  var BaseBehaviour;

  BaseBehaviour = (function() {

    function BaseBehaviour(entity, world) {
      this.entity = entity;
      this.world = world;
    }

    BaseBehaviour.prototype.update = function() {
      var bodyPos, sprite, _i, _len, _ref;
      _ref = this.entity.sprites;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sprite = _ref[_i];
        sprite.update();
      }
      if (this.entity.body != null) {
        this.entity.body.update();
        bodyPos = this.entity.body.position();
        if (this.entity.x !== bodyPos.x || this.entity.y !== bodyPos.y) {
          return this.entity.updatePos();
        }
      }
    };

    return BaseBehaviour;

  })();

  module.exports = BaseBehaviour;

}).call(this);
