// Generated by CoffeeScript 1.6.1
(function() {
  var BaseModal, PauseModal, device, views,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModal = require('./BaseModal');

  device = require('../../core/device');

  views = require('../../core/views');

  /*
  ## Pause Modal class
  
  Modal shown when pausing
  Read BaseModal for more
  */


  PauseModal = (function(_super) {

    __extends(PauseModal, _super);

    PauseModal.prototype.templateName = 'modal-pause';

    PauseModal.prototype.classNames = 'modal-pause';

    function PauseModal(wrap, context, options) {
      this.wrap = wrap;
      this.context = context;
      if (options == null) {
        options = {};
      }
      this.game = options.game;
      this.levelName = options.levelName;
      this.game.world.stop();
      PauseModal.__super__.constructor.apply(this, arguments);
    }

    PauseModal.prototype.bind = function() {
      var _this = this;
      PauseModal.__super__.bind.apply(this, arguments);
      this.inner.on(device.getEvent('click'), '[data-role="restart"]', function(e) {
        _this.game.restart();
        return e.preventDefault();
      });
      this.inner.on(device.getEvent('click'), '[data-role="resume"]', function(e) {
        _this.close();
        _this.game.world.play();
        return e.preventDefault();
      });
      return this.inner.on(device.getEvent('click'), '[data-role="back"]', function(e) {
        views.open('levels', 'slide-left');
        return e.preventDefault();
      });
    };

    return PauseModal;

  })(BaseModal);

  module.exports = PauseModal;

}).call(this);
