// Generated by CoffeeScript 1.6.1

/*
## Game Configuration module

Exports a few setting used across game modules
*/


(function() {

  module.exports = {
    wallsColor: '#a2bfc9',
    gameDataPath: 'game-data'
  };

}).call(this);
